# Generated by Django 5.2.6 on 2025-09-13 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('passproduct_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('brand', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('countInStock', models.IntegerField()),
                ('image', models.ImageField(upload_to='products_images/')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
