# Generated by Django 5.2.6 on 2025-09-13 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='passproduct_id',
            new_name='product_id',
        ),
    ]
